;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	end-of-buffer
	))

(setq mc/cmds-to-run-once
      '(
	dired-mouse-find-file-other-window
	dired-previous-line
	kill-region
	mouse-set-region
	))
