;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-lt-gt
	c-electric-star
	c-indent-line-or-region
	end-of-buffer
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-colon
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	dired-mouse-find-file-other-window
	dired-previous-line
	electric-pair-delete-pair
	find-file
	indent-for-tab-command
	kill-region
	mouse-drag-mode-line
	mouse-select-window
	mouse-set-region
	nk/format-code
	shell-command
	tab-line-select-tab
	))
